use navigate and route, clean up code
JustBrandonLim/ICT2106_P2_Project pull request #7
Opened 2023-02-09 19:29 UTC by brucewzj99

# Description

Please include a summary of the changes and the related issue. 
Please also include relevant screenshot and context. 

Fixes # (issue)
Clean up code, using of routerlink, navigate
Fix account creation

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Register and login of account

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-10 02:50 UTC, fabianchua6 requested changes
noiceee

2023-02-10 02:50 UTC, fabianchua6 commented on SmartHomeManager/SmartHomeManager.View/src/pages/account/Login.js
> +import { Link as RouterLink } from "react-router-dom";
can combine into one line

2023-02-10 02:50 UTC, fabianchua6 commented on SmartHomeManager/SmartHomeManager.View/src/pages/account/Register.js
> +import { Link as RouterLink } from "react-router-dom";
here as well

2023-02-10 05:45 UTC, brucewzj99 commented
Need to make more chances

2023-02-10 08:22 UTC, DoubleBounce approved these changes
LGTM

2023-02-14 06:37 UTC, fabianchua6 approved these changes

2023-02-14 06:39 UTC, merged